### ISSUE TITLE
unexpected end of JSON

### ISSUE THREAD

**Issue by theclickman** [s32x/anirip#43] opened 2019-11-17 21:33 UTC
Several episodes are failing due to that messages. Seems to be the source JSON file for subtitles that is corrupted/get corrupted in the transfer.

I am updated to last version from a few days ago.
Also got an episode that fail with "exit Status 1" on the download of the video.

Thanks

**Comment by turtletowerz** [comment] 2019-11-18 02:03
Could you please provide a little bit more context or images. Knowing specifically what show is failing as well as what OS you use would also be helpful

I'm thinking of making a pull request for better error handling, but for now if you could provide more information about the show. "exit status 1" is the vague error exec.Command returns when ffmpeg fails, so it could be failing at the video or at the merging of subtitles

**Comment by theclickman** [comment] 2019-11-18 02:39
I am  not at home so can't give you screenshot but can add this: 

The unexpected end of JSON appear after "Downloading subtitles" and the "exit status 1" after "Downloading video". It is not on all episodes it is just a few of them but always the same. 

I am on Windows 10 version from this year and last updates. Anirip code also to last le el of code. Will provide screenshot as soon as I can.

**Comment by theclickman** [comment] 2019-11-20 19:48
Sorry it took so long, my son is sick.
Here the screenshot.
On this show, I got the JSON error (on 105 and 108) and the Exit Status 1 error (on 106)

![image](https://user-images.githubusercontent.com/38191912/69272311-71cca300-0ba4-11ea-96d6-04d3a02dbbea.png)

The others show I get only get the JSON error. 3 episodes also, all in the same timeframe of release

**Comment by turtletowerz** [comment] 2019-11-21 22:51
I'm not quite sure what the issue here was, but I have since updated the way subtitles are downloaded in #45 and it will (hopefully) fix your problem. I could not reproduce the issue with the video not downloading, so all I can say for now is check and make sure `ffmpeg` is installed. If the PR gets merged that may also fix it

Screenshot of it working on Black Clover:

![2019-11-21_17-37-36](https://user-images.githubusercontent.com/29441515/69383386-80d85180-0c87-11ea-9ae8-ed9e42cf7444.png)

**Comment by theclickman** [comment] 2019-11-22 00:07
waiting for the merge to be done to test.

**Comment by theclickman** [comment] 2019-11-25 15:16
just see that you screenshot is on the very first episodes, but my error did happen on the most recent one (105, 106 and 108). 

It would be nice for testing purpose to have a way to target a single episode rather than scanning the entire show every time btw.

**Comment by turtletowerz** [comment] 2019-11-25 18:00
Oh my mistake, I thought those were the earlier episodes. 

As for individual episodes, it's also something I plan on making a separate commit for. There's a lot that could be added or improved in this project which is why I made my own rewrite of this. It's not currently public and I don't really want to advertise it here but it contains solutions for a lot of issues that are present with this, so I may slowly try to fix those here.

**Closed** 2019-11-27 03:27 UTC

**Comment by turtletowerz** [comment] 2019-11-27 04:00
Let me know if it continues to error after this, I'll work on some solution for individual episode downloads in the meantime

**Comment by theclickman** [comment] 2019-11-27 13:50
Oops?

C:\>go get -u s32x.com/anirip
# s32x.com/anirip/crunchyroll
Users\live\go\src\s32x.com\anirip\crunchyroll\subtitle.go:43:13: undefined: strings.ReplaceAll

something off with the code.

**Comment by theclickman** [comment] 2019-11-27 13:56
ok, work better after updating Go itself (I was 1.10.1, updated to 1.13.4)

**Comment by theclickman** [comment] 2019-11-27 16:37
Confirmed Fixed after the double update of Go and the code. Not even got that "Exit Status 1" anymore. My episodes are up to date now.

**Comment by s32x** [comment] 2019-11-27 18:08
That's great to hear! Thanks, @turtletowerz for the help with this.

**Comment by turtletowerz** [comment] 2019-11-28 05:26
Glad to hear it was fixed!
